In [1]:
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
import time

# 创建Chrome浏览器选项
options = Options()
options.add_argument('--headless')  # 无头模式，不显示浏览器界面
options.add_argument('--disable-gpu')  # 禁用GPU加速

# 模拟手机浏览器
options.add_argument('--user-agent=Mozilla/5.0 (iPhone; CPU iPhone OS 14_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1 Mobile/15E148 Safari/604.1')
path_to_chromedriver = r'C:\Users\97696\Downloads\chromedriver.exe'
# 创建Chrome浏览器实例
driver = webdriver.Chrome(path_to_chromedriver, options=options)

# 打开网页
urls = 'https://cstv13.com:8443/'
driver.get(urls)
time.sleep(2)

# 获取页面高度
scroll_height = driver.execute_script("return document.documentElement.scrollHeight")

# 设置视口大小和网页高度
driver.set_window_size(375, scroll_height)

# 截取整个网页的完整长屏
driver.save_screenshot('screenshot_m3.png')

# 关闭浏览器
driver.quit()


C:\Users\97696\AppData\Local\Temp\ipykernel_45908\2598003019.py:13: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(path_to_chromedriver, options=options)


In [7]:
# st = 'cstv13.com:8443,asdf'
st = 'https://cstv13.com:8443/'
import re 
result = ''.join(re.findall(r'[A-Za-z0-9]', st)) 
print(result)


httpscstv13com8443


In [3]:
import re
st = "hello,world!!%[545]你好234世界。。。"
result = ''.join(re.findall(r'[A-Za-z0-9]', st)) 
print(result)

helloworld545234


In [9]:
# -*- coding: utf-8 -*-
from selenium import webdriver
import time


def take_screenshot(url, save_fn="capture.png"):
    # browser = webdriver.Firefox() # Get local session of firefox
    #谷歌浏览器截取当前窗口网页
    chromedriver = r'C:\Users\97696\Downloads\chromedriver.exe'
    browser = webdriver.Chrome(chromedriver)
    #phantomjs截取整张网页
    # browser = webdriver.PhantomJS()
    browser.set_window_size(1200, 900)
    browser.get(url) # Load page
    #将页面的滚动条拖到最下方，然后再拖回顶部
    browser.execute_script("""
        (function () {
            var y = 0;
            var step = 100;
            window.scroll(0, 0);

            function f() {
                if (y < document.body.scrollHeight) {
                    y += step;
                    window.scroll(0, y);
                    setTimeout(f, 100);
                } else {
                    window.scroll(0, 0);
                    document.title += "scroll-done";
                }
            }

            setTimeout(f, 1000);
        })();
    """)

    for i in range(30):
        if "scroll-done" in browser.title:
            break
        time.sleep(10)

    browser.save_screenshot(save_fn)
    browser.close()


if __name__ == "__main__":

    take_screenshot("https://www.zhihu.com/tardis/zm/art/460551008?source_id=1003")

C:\Users\97696\AppData\Local\Temp\ipykernel_45908\1648690827.py:10: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  browser = webdriver.Chrome(chromedriver)


In [2]:
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

# 设置手机浏览器选项
mobile_emulation = {
    "deviceName": "iPhone X"
}

chrome_options = Options()
chrome_options.add_experimental_option("mobileEmulation", mobile_emulation)

# 启动Chrome浏览器
# driver = webdriver.Chrome(executable_path='path_to_chromedriver', options=chrome_options)
path_to_chromedriver = r'C:\Users\97696\Downloads\chromedriver.exe'
# 创建Chrome浏览器实例
driver = webdriver.Chrome(path_to_chromedriver, options=chrome_options)

# 打开网站
driver.get('https://cstv13.com:8443/')

# 等待页面加载完成
wait = WebDriverWait(driver, 10)
wait.until(EC.presence_of_element_located((By.TAG_NAME, "body")))

# 设置长宽为手机屏幕的尺寸
body = driver.find_element(By.TAG_NAME, 'body')
height = body.size["height"]
width = body.size["width"]
driver.set_window_size(width, height)

# 截取整个页面的长图
screenshot = driver.find_element(By.TAG_NAME, 'body').screenshot_as_png

# 保存截图
with open("screenshot.png", "wb") as file:
    file.write(screenshot)

# 关闭浏览器
driver.quit()


C:\Users\97696\AppData\Local\Temp\ipykernel_61952\3328496040.py:19: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(path_to_chromedriver, options=chrome_options)


In [3]:
from PIL import Image

def remove_solid_color(image_path):
    # 打开图像
    image = Image.open(image_path)
    
    # 转换为RGB模式（如果不是）
    image = image.convert("RGB")
    
    # 获取图像的尺寸
    width, height = image.size
    
    # 设置阈值，用于判断是否为全白或全黑像素
    threshold = 5
    
    # 循环遍历图像的每个像素
    for y in range(height):
        for x in range(width):
            # 获取像素的RGB值
            r, g, b = image.getpixel((x, y))
            
            # 判断像素是否为全白或全黑
            if abs(r - 255) < threshold and abs(g - 255) < threshold and abs(b - 255) < threshold:
                image.putpixel((x, y), (0, 0, 0))  # 将全白像素设置为黑色
            elif abs(r) < threshold and abs(g) < threshold and abs(b) < threshold:
                image.putpixel((x, y), (255, 255, 255))  # 将全黑像素设置为白色
    
    # 保存处理后的图像
    image.save("processed_image.png")

# 调用函数并传入图像路径
remove_solid_color('./httpah1010com.png')


In [4]:
from PIL import Image

def crop_white_regions(image_path):
    # 打开图像
    image = Image.open(image_path)
    
    # 转换为RGB模式（如果不是）
    image = image.convert("RGB")
    
    # 获取图像的尺寸
    width, height = image.size
    
    # 设置阈值，用于判断像素是否为白色
    threshold = 200
    
    # 初始化裁剪区域的坐标
    left = width
    top = height
    right = 0
    bottom = 0
    
    # 循环遍历图像的每个像素
    for y in range(height):
        for x in range(width):
            # 获取像素的RGB值
            r, g, b = image.getpixel((x, y))
            
            # 判断像素是否为白色
            if r >= threshold and g >= threshold and b >= threshold:
                # 更新裁剪区域的坐标
                left = min(left, x)
                top = min(top, y)
                right = max(right, x)
                bottom = max(bottom, y)
    
    # 裁剪图像
    cropped_image = image.crop((left, top, right + 1, bottom + 1))
    
    # 保存裁剪后的图像
    cropped_image.save("cropped_image.png")

# 调用函数并传入图像路径
crop_white_regions("./httpah1010com.png")


In [66]:
import cv2
img = cv2.imread('./httpah1010com.png')
h,w,c = img.shape
pixel = img[300][200]
print(pixel)

[198 230 252]


In [57]:
import cv2
img = cv2.imread('./httpah1010com.png')
h,w,c = img.shape
# 循环遍历图像的每个像素
for y in range(h):
    target = img[y][30][0]
    for i in range(100):
        for j in range(200):
            if img[y+i][j][0]==target:
                continue
            else:
                break
        
print(img[9000:9100,300:310,0])
# print(img[9000:9100,345:355,0])
cv2.imwrite("./cv_cut.jpg",img[:4800])

[[246 246 246 246 246 246 246 246 246 246]
 [246 246 246 246 246 246 246 246 246 246]
 [246 246 246 246 246 246 246 246 246 246]
 [246 246 246 246 246 246 246 246 246 246]
 [246 246 246 246 246 246 246 246 246 246]
 [246 246 246 246 246 246 246 246 246 246]
 [246 246 246 246 246 246 246 246 246 246]
 [246 246 246 246 246 246 246 246 246 246]
 [246 246 246 246 246 246 246 246 246 246]
 [246 246 246 246 246 246 246 246 246 246]
 [246 246 246 246 246 246 246 246 246 246]
 [246 246 246 246 246 246 246 246 246 246]
 [246 246 246 246 246 246 246 246 246 246]
 [246 246 246 246 246 246 246 246 246 246]
 [246 246 246 246 246 246 246 246 246 246]
 [246 246 246 246 246 246 246 246 246 246]
 [246 246 246 246 246 246 246 246 246 246]
 [246 246 246 246 246 246 246 246 246 246]
 [246 246 246 246 246 246 246 246 246 246]
 [246 246 246 246 246 246 246 246 246 246]
 [246 246 246 246 246 246 246 246 246 246]
 [246 246 246 246 246 246 246 246 246 246]
 [246 246 246 246 246 246 246 246 246 246]
 [246 246 2

True

In [61]:
import numpy as np
t = [[246,246, 246, 246, 246, 246, 246, 246 ,246 ,246],
 [246 ,246 ,246 ,246 ,246 ,246 ,246 ,246 ,246 ,246,],
 [246 ,246, 246, 246, 246 ,246, 246, 246, 246, 246]]
t_np = np.array(t)

In [62]:
print(t_np.shape)
r,c = t_np.shape
target = t_np[0][0]
for i in range(r):
    for j in range(c):
        if t_np[i][j]==target:
            continue
        else:
            break

(3, 10)
